name: Bug Report
description: Report a bug in sops-operator
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create SopsSecret with...
        2. Apply to cluster...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: sopssecret
    attributes:
      label: SopsSecret YAML (redacted)
      description: The SopsSecret manifest (remove sensitive data)
      render: yaml
      placeholder: |
        apiVersion: secrets.scalaric.io/v1alpha1
        kind: SopsSecret
        metadata:
          name: example
        spec:
          sopsSecret: |
            # redacted

  - type: textarea
    id: logs
    attributes:
      label: Operator Logs
      description: Relevant logs from the operator
      render: shell

  - type: input
    id: version
    attributes:
      label: Operator Version
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: k8s-version
    attributes:
      label: Kubernetes Version
      placeholder: "v1.28.0"

  - type: dropdown
    id: encryption
    attributes:
      label: Encryption Backend
      options:
        - AGE
        - Other (please specify in description)
    validations:
      required: true
