//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgeRecipient) DeepCopyInto(out *AgeRecipient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgeRecipient.
func (in *AgeRecipient) DeepCopy() *AgeRecipient {
	if in == nil {
		return nil
	}
	out := new(AgeRecipient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureKVKey) DeepCopyInto(out *AzureKVKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureKVKey.
func (in *AzureKVKey) DeepCopy() *AzureKVKey {
	if in == nil {
		return nil
	}
	out := new(AzureKVKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPKMSKey) DeepCopyInto(out *GCPKMSKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPKMSKey.
func (in *GCPKMSKey) DeepCopy() *GCPKMSKey {
	if in == nil {
		return nil
	}
	out := new(GCPKMSKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HCVaultKey) DeepCopyInto(out *HCVaultKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HCVaultKey.
func (in *HCVaultKey) DeepCopy() *HCVaultKey {
	if in == nil {
		return nil
	}
	out := new(HCVaultKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMSKey) DeepCopyInto(out *KMSKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMSKey.
func (in *KMSKey) DeepCopy() *KMSKey {
	if in == nil {
		return nil
	}
	out := new(KMSKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsMetadata) DeepCopyInto(out *SopsMetadata) {
	*out = *in
	if in.Age != nil {
		in, out := &in.Age, &out.Age
		*out = make([]AgeRecipient, len(*in))
		copy(*out, *in)
	}
	if in.KMS != nil {
		in, out := &in.KMS, &out.KMS
		*out = make([]KMSKey, len(*in))
		copy(*out, *in)
	}
	if in.GCPKMS != nil {
		in, out := &in.GCPKMS, &out.GCPKMS
		*out = make([]GCPKMSKey, len(*in))
		copy(*out, *in)
	}
	if in.AzureKV != nil {
		in, out := &in.AzureKV, &out.AzureKV
		*out = make([]AzureKVKey, len(*in))
		copy(*out, *in)
	}
	if in.HCVault != nil {
		in, out := &in.HCVault, &out.HCVault
		*out = make([]HCVaultKey, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsMetadata.
func (in *SopsMetadata) DeepCopy() *SopsMetadata {
	if in == nil {
		return nil
	}
	out := new(SopsMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecret) DeepCopyInto(out *SopsSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.Sops != nil {
		in, out := &in.Sops, &out.Sops
		*out = new(SopsMetadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecret.
func (in *SopsSecret) DeepCopy() *SopsSecret {
	if in == nil {
		return nil
	}
	out := new(SopsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretList) DeepCopyInto(out *SopsSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SopsSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretList.
func (in *SopsSecretList) DeepCopy() *SopsSecretList {
	if in == nil {
		return nil
	}
	out := new(SopsSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretSpec) DeepCopyInto(out *SopsSecretSpec) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]v1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.SecretLabels != nil {
		in, out := &in.SecretLabels, &out.SecretLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SecretAnnotations != nil {
		in, out := &in.SecretAnnotations, &out.SecretAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretSpec.
func (in *SopsSecretSpec) DeepCopy() *SopsSecretSpec {
	if in == nil {
		return nil
	}
	out := new(SopsSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretStatus) DeepCopyInto(out *SopsSecretStatus) {
	*out = *in
	if in.LastDecryptedTime != nil {
		in, out := &in.LastDecryptedTime, &out.LastDecryptedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretStatus.
func (in *SopsSecretStatus) DeepCopy() *SopsSecretStatus {
	if in == nil {
		return nil
	}
	out := new(SopsSecretStatus)
	in.DeepCopyInto(out)
	return out
}
